server:
  port: 8080

#spring:
  #datasource:
    #url: jdbc:postgresql://db:5432/comerciosdb
    #username: postgres
    #password: example

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update #lo debo cambiar a validate en desarrollo
    properties:
      hibernate:
        format_sql: true

flyway:
  enabled: true
  locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:change_this_secret}
  access-expiration-ms: 900000          # 15 min
  refresh-expiration-ms: 604800000      # 7 días

app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://front.vercel.app"
